### ISSUE TITLE
转换格式有误

### ISSUE THREAD

**Issue by jackyon** [vilien/xmlstring2json#1]
`<data>
    <row CompCode="gzkl" CompName="广州市客轮公司" Tel="" Addr="" Notes="0"/>
    <row CompCode="gzstar" CompName="广州之星游轮有限公司" Tel="" Addr="" Notes=""/>
    <row CompCode="0.1" CompName="公交一分公司·南海神" Tel="" Addr="" Notes="00"/>
    <row CompCode="mzkt" CompName="梅州客通" Tel="" Addr="" Notes=""/>
    <row CompCode="gfzq" CompName="广州之星（代售）" Tel="" Addr="" Notes=""/>
    <row CompCode="0.2" CompName="广州之星·南海神" Tel="" Addr="" Notes=""/>
    <row CompCode="0.3" CompName="公交二分公司" Tel="" Addr="" Notes=""/>
    <row CompCode="gzch" CompName="广州从化流溪游船有限公司" Tel="" Addr="" Notes=""/>
</data>`

像上面的代码，无法正常转换， 如图:
<img width="578" alt="2017-07-26 9 42 43" src="https://user-images.githubusercontent.com/1758938/28600768-cf785f94-71e6-11e7-8b3a-413fd332bfda.png">

**Comment by vilien** [comment]
感谢！之前对自闭合标签的处理考虑不周，现已修复。
